#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
cd ./ffc-mpdp-frontend && \
  docker-compose build

cd "${projectRoot}"
cd ./ffc-mpdp-backend && \
  docker-compose build
