#!/usr/bin/env sh

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

cd "${projectRoot}"

test -d ffc-mpdp-frontend\
  && >&2 echo "The 'ffc-mpdp-frontend' repository already exists. Skipping." \
  || git clone https://github.com/DEFRA/ffc-mpdp-frontend.git

test -d ffc-mpdp-backend\
  && >&2 echo "The 'ffc-mpdp-backend' repository already exists. Skipping." \
  || git clone https://github.com/DEFRA/ffc-mpdp-backend.git

