#!/usr/bin/bash

totalCpu=0
totalMemory=0
totalPods=0

# Arrange in alphabetical order
arr=(
  "ffc-mpdp-frontend"
  "ffc-mpdp-backend"
  )

for i in "${arr[@]}"
do
  echo "Getting values from $i"
  valuesFile="https://raw.githubusercontent.com/DEFRA/$i/main/helm/$i/values.yaml"
  maxReplicas=$(curl --silent $valuesFile | yq e '.deployment.maxReplicas' -)
  # if maxReplicas does not exist get replicas instead
  if [ "$maxReplicas" = "null" ]; then
    maxReplicas=$(curl --silent $valuesFile | yq e '.deployment.replicas' -)
  fi
  # if replicas does not exist set to 1
  if [ "$maxReplicas" = "null" ]; then
    maxReplicas=1
  fi
  cpu=$(curl --silent $valuesFile | yq e '.container.requestCpu' - | sed -E 's/[A-Za-z]//g')
  memory=$(curl --silent $valuesFile | yq e '.container.limitMemory' - | sed -E 's/[A-Za-z]//g')
  totalCpu=$(($totalCpu + $cpu * $maxReplicas))
  totalMemory=$(($totalMemory + $memory * $maxReplicas))
  totalPods=$(($totalPods + $maxReplicas))
done

echo "CPU required: $totalCpu"
echo "Memory required: $totalMemory"
echo "Pods required: $totalPods"
