#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

./ffc-mpdp-frontend/scripts/start -d $@;
./ffc-mpdp-backend/scripts/start -d $@;
